- CMakeLists.txt
- include/xwidgets/xmock_interpreter.hpp
- include/xwidgets/xobject.hpp
- include/xwidgets/xwidget.hpp
- include/xwidgets/xwidgets_config.hpp
- include/xwidgets/xwidgets_interpreter.hpp
- src/xobject.cpp
- src/xwidgets_interpreter.cpp
- test/CMakeLists.txt
- test/test_xslider.cpp
@SylvainCorlay The slider test throws an exception, I don't know yet if this is due to the mock interpreter or to another bug in `xeus`, I will investigate later.
> cmake, mock interpreter and first test

- include/xwidgets/xobject.hpp
This is the same mechanism as in ipywidgets' property lock.
cc @jasongrout @JohanMabille
> Prevent bouncing of front-end updates

- include/xwidgets/xbutton.hpp
- include/xwidgets/xobject.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xwidget.hpp
- notebooks/xwidget.ipynb
> Decouple final widgets from CRTP bases.

- CMakeLists.txt
- include/xwidgets/xbutton.hpp
- include/xwidgets/xlayout.hpp
- include/xwidgets/xnumber.hpp
- include/xwidgets/xnumeral.hpp
- include/xwidgets/xobject.hpp
- include/xwidgets/xprogress.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xtransport.hpp
- include/xwidgets/xwidget.hpp
- notebooks/xwidget.ipynb
> Add numerical input widget

- .travis.yml
- CMakeLists.txt
- include/xwidgets/xbutton.hpp
- include/xwidgets/xholder.hpp
- include/xwidgets/xholder_id.hpp
- include/xwidgets/xlayout.hpp
- include/xwidgets/xlink.hpp
- include/xwidgets/xobject.hpp
- include/xwidgets/xprogress.hpp
- include/xwidgets/xregistry.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xtextarea.hpp
- include/xwidgets/xtransport.hpp
This requires a release of xtl including the new xoptional feature.
> Use xoptional from the xtl

- README.md
- include/xwidgets/xholder.hpp
- include/xwidgets/xregistry.hpp
- include/xwidgets/xtransport.hpp
Requires a release of xeus with the new xguid.
> Use new xguid - update to xeus 0.6.0

- README.md
- include/xwidgets/xholder.hpp
- include/xwidgets/xholder_id.hpp
Depends on https://github.com/QuantStack/xtl/pull/15 in an xtl release.
> Improve xholder downcast

- include/xwidgets/xlink.hpp
- notebooks/xwidgets.ipynb
> Adding directional link

- include/xwidgets/xslider.hpp
> Enable slider validation

- include/xwidgets/xdropdown.hpp
- include/xwidgets/xnumber.hpp
- include/xwidgets/xradiobuttons.hpp
- include/xwidgets/xselect.hpp
- include/xwidgets/xselection.hpp
- include/xwidgets/xselectionslider.hpp
- notebooks/xwidgets.ipynb
> Add multiple selection widget

- CMakeLists.txt
- include/xwidgets/xaccordion.hpp
- include/xwidgets/xboolean.hpp
- include/xwidgets/xcheckbox.hpp
- include/xwidgets/xcontroller.hpp
- include/xwidgets/xlink.hpp
- include/xwidgets/xnumber.hpp
- include/xwidgets/xnumeral.hpp
- include/xwidgets/xpassword.hpp
- include/xwidgets/xplay.hpp
- include/xwidgets/xprogress.hpp
- include/xwidgets/xselect.hpp
- include/xwidgets/xselection.hpp
- include/xwidgets/xselection_container.hpp
- include/xwidgets/xselectionslider.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xstring.hpp
- include/xwidgets/xtab.hpp
- include/xwidgets/xtext.hpp
- include/xwidgets/xtextarea.hpp
- include/xwidgets/xtogglebutton.hpp
- include/xwidgets/xtogglebuttons.hpp
- notebooks/xwidgets.ipynb
> Add selection container widgets

- include/xwidgets/xselection_container.hpp
- notebooks/xwidgets.ipynb
> Add tabs and accordion titles

- CMakeLists.txt
- include/xwidgets/xbutton.hpp
- include/xwidgets/xcheckbox.hpp
- include/xwidgets/xcolor.hpp
- include/xwidgets/xcolor_picker.hpp
- include/xwidgets/xholder.hpp
- include/xwidgets/xprogress.hpp
- include/xwidgets/xselection_container.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xtogglebuttons.hpp
- include/xwidgets/xwidget.hpp
- notebooks/xwidgets.ipynb
> Add color picker widget

- include/xwidgets/xselection_container.hpp
By consistency with ipywidgets.
> Set default selected index to 0

- include/xwidgets/xslider.hpp
Like in other validated widgets.
> Separate setup-properties in slider constructor

- include/xwidgets/xbox.hpp
- notebooks/xwidgets.ipynb
This notebook change is about a missing include.
> Fix xbox.add

- include/xwidgets/xwidget.hpp
> Add missing _dom_classes attribute

- include/xwidgets/xtransport.hpp
The no-bounce mechanism is meant to avoid race condition with messages bouncing back to the front-end after an update.
In short, when receiving a stream of update messages from e.g. a slider value changing continuously, if the traitlets / xproperty change events are sent back to the front-end, this would cause the slider to move back to previous values.
To prevent this sort of race condition, during the handling of the update message, we do
```cpp
m_hold = std::addressof(message);
// processing of the message
m_hold = nullptr;	
```
Then, during the synchronous precessing of the message, `m_hold` holds a pointer on the message being processed.
Then, in the `notify` method called on property changes, we check if `m_hold` is set before sending a message back to the front-end. If `m_hold` is …
> Cleanup the no-bounce mechanism

- include/xwidgets/xholder.hpp
- test/test_xholder.cpp
Fixes #138 
@SylvainCorlay Let me know if that's ok for you.
> xholder_shared implementation

- include/xwidgets/xcolor_picker.hpp
- include/xwidgets/xlayout.hpp
- include/xwidgets/xtogglebuttons.hpp
- include/xwidgets/xwidget.hpp
Repeated property in color picker.
Formatting in xwidget, xlayout, togglebuttons.
> Fix color picker and formatting

- CMakeLists.txt
- include/xwidgets/xoutput.hpp
- notebooks/xwidgets.ipynb
- src/xoutput.cpp
Instantiate and display an output widget:
```cpp
#include "xwidgets/xoutput.hpp"
xw::output out;
out
```
Display content in that output:
```cpp
#include <iostream>
{
// Anything printed or display in that scope after `guard` is created
// will show in the output widget.
auto guard = out.guard();
std::cout << "hello" << std::endl;
}
```
> Add output widget

- .appveyor.yml
- .travis.yml
> Update xeus to 0.24.0

- .appveyor.yml
- CMakeLists.txt
- include/xwidgets/xcontroller.hpp
- include/xwidgets/xtarget.hpp
- include/xwidgets/xtransport.hpp
- src/xtarget.cpp
Another simple PR to rebase #199 upon.
> Split xtarget

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/unix-build.yml
- azure-pipelines.yml
- environment-dev.yml
Adding Azure config only, no need to wait for the CI.
> Added Azure Pipelines

- CMakeLists.txt
- xwidgetsConfig.cmake.in
This PR adds the static library compilation and fixes #220.
I have marked it as a draft because as of now I have not been able to test if the shared library compilation still works (I need the static libraries because I do not have all the shared dependencies installed)
> Add static build support

- .azure-pipelines/azure-pipelines-linux.yml
- notebooks/xwidgets.ipynb
https://github.com/jupyterlab/jupyterlab/issues/5090
> Fixup metadata in example notebook causing outputs to be scrolled even after re-execution

- CMakeLists.txt
- xwidgetsConfig.cmake.in
> Fixed typo in xproperty dependency

- CMakeLists.txt
- environment-dev.yml
- include/xwidgets/xall.hpp
- include/xwidgets/xbutton.hpp
- include/xwidgets/xlayout.hpp
- include/xwidgets/xoutput.hpp
- include/xwidgets/xpassword.hpp
- include/xwidgets/xplay.hpp
- include/xwidgets/xselection_container.hpp
- include/xwidgets/xselectionslider.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xtogglebuttons.hpp
- include/xwidgets/xwidgets_config.hpp
- src/xmedia.cpp
- test/CMakeLists.txt
- test/jupyterwidgetmodels.latest.json
- test/test_widget_model.cpp
- test/test_xwidgets.cpp
Fix and update the widget attributes for IPyWidget 8.0 #238.
Adds a test that uses the IPyWidgets schema to diagnose missing attributes.
Some visual and style attributes are missing, but since this PR is getting big, I prefer to submit this for review.
> Fix and update widget attributes

- .cmake-format.json
- .pre-commit-config.yaml
- CMakeLists.txt
- environment-dev.yml
- test/CMakeLists.txt
- Update pre-commit versions
- Add cmake-format
- Apply cmake-format
- Add GHA schema check
> CMake format and GHA schema checks

- CMakeLists.txt
- include/xwidgets/xall.hpp
- include/xwidgets/xbutton.hpp
- include/xwidgets/xcheckbox.hpp
- include/xwidgets/xcolor_picker.hpp
- include/xwidgets/xdescription_style.hpp
- include/xwidgets/xhtml.hpp
- include/xwidgets/xlabel.hpp
- include/xwidgets/xlink.hpp
- include/xwidgets/xmedia.hpp
- include/xwidgets/xnumeral.hpp
- include/xwidgets/xpassword.hpp
- include/xwidgets/xplay.hpp
- include/xwidgets/xradiobuttons.hpp
- include/xwidgets/xselection.hpp
- include/xwidgets/xselectionslider.hpp
- include/xwidgets/xslider.hpp
- include/xwidgets/xtext.hpp
- include/xwidgets/xtextarea.hpp
- include/xwidgets/xtogglebutton.hpp
- include/xwidgets/xvalid.hpp
- src/xcheckbox.cpp
- src/xdescription_style.cpp
- src/xhtml.cpp
- src/xtext.cpp
- src/xtogglebutton.cpp
- test/test_widget_model.cpp
> Add missing styles

- .clang-format
- include/xwidgets/xbinary.hpp
- include/xwidgets/xbutton.hpp
- include/xwidgets/xcontroller.hpp
- include/xwidgets/xfactory.hpp
- include/xwidgets/xholder.hpp
- include/xwidgets/xtext.hpp
- src/xaudio.cpp
- src/xbinary.cpp
- src/xbutton.cpp
- src/xholder_id.cpp
- src/ximage.cpp
- src/xlayout.cpp
- src/xprogress.cpp
- src/xslider.cpp
- src/xtarget.cpp
- src/xtarget.hpp
- src/xtogglebuttons.cpp
- src/xvideo.cpp
- test/main.cpp
- test/test_widget_model.cpp
- test/test_xholder.cpp
Fix warnings on aggressive setting.
> Code improvments

- .github/workflows/main.yml
- environment-dev.yml
- notebooks/xwidgets.ipynb
- Run notebook without error
- Simplify GHA workflow
- Run notebook in CI
> Test notebook in CI

- include/xwidgets/xall.hpp
- include/xwidgets/xbox.hpp
- include/xwidgets/xlabel.hpp
- include/xwidgets/xstyle.hpp
- test/test_widget_model.cpp
- test/test_xwidgets.cpp
- Add a test for missing wigets
- Fix some error on currently available widgets.
- Exclude widgets tracked in #249 from the test (so that we can use the test for now).
> Fix some missing widgets and test for missing ones

- src/xcommon.cpp
Raised, but not implemented in #251
> Change definition of true environment variable to match Jupyter
