jupyter-xeus/xwidgets

include/xwidgets/xbutton.hpp, include/xwidgets/xlayout.hpp, include/xwidgets/xslider.hpp, include/xwidgets/xtransport.hpp
The base widget had a collection of callbacks for custom messages.
This collection was copied according to the value semantics of the base widget.
When the callback collection had methods of the current widget registered, it would still point to a member of the moved-from widget after a move.
=> Fixup button value semantics

include/xwidgets/xboolean.hpp, include/xwidgets/xbox.hpp, include/xwidgets/xbutton.hpp, include/xwidgets/xcheckbox.hpp, include/xwidgets/xholder.hpp, include/xwidgets/xholder_id.hpp, include/xwidgets/xhtml.hpp, include/xwidgets/xlabel.hpp, include/xwidgets/xlayout.hpp, include/xwidgets/xlink.hpp, include/xwidgets/xmaterialize.hpp, include/xwidgets/xnumber.hpp, include/xwidgets/xnumeral.hpp, include/xwidgets/xobject.hpp, include/xwidgets/xpassword.hpp, include/xwidgets/xplay.hpp, include/xwidgets/xprogress.hpp, include/xwidgets/xregistry.hpp, include/xwidgets/xslider.hpp, include/xwidgets/xstring.hpp, include/xwidgets/xstyle.hpp, include/xwidgets/xtext.hpp, include/xwidgets/xtextarea.hpp, include/xwidgets/xtogglebutton.hpp, include/xwidgets/xtransport.hpp, include/xwidgets/xvalid.hpp, include/xwidgets/xwidget.hpp, test/test_xwidgets.cpp
@SylvainCorlay I had to remane ``layout`` (the type) into ``wlayout``, otherwise theire is a conflict in the ``xwidget`` class between the ``layout`` type and the ``layout`` member.
=> widgets have now their own namespace

include/xwidgets/xboolean.hpp, include/xwidgets/xbox.hpp, include/xwidgets/xbutton.hpp, include/xwidgets/xcheckbox.hpp, include/xwidgets/xhtml.hpp, include/xwidgets/xlabel.hpp, include/xwidgets/xlayout.hpp, include/xwidgets/xlink.hpp, include/xwidgets/xmaterialize.hpp, include/xwidgets/xnumber.hpp, include/xwidgets/xnumeral.hpp, include/xwidgets/xpassword.hpp, include/xwidgets/xplay.hpp, include/xwidgets/xprogress.hpp, include/xwidgets/xslider.hpp, include/xwidgets/xstring.hpp, include/xwidgets/xstyle.hpp, include/xwidgets/xtext.hpp, include/xwidgets/xtextarea.hpp, include/xwidgets/xtogglebutton.hpp, include/xwidgets/xtransport.hpp, include/xwidgets/xvalid.hpp, include/xwidgets/xwidget.hpp
- Make all the CRTP base constructors and affectation operators protected.
- Replace `make_widget<widget_type>` with a call to a constructor of `xgenerator<Xwidget_type>`
- Add a `using foobar_generator = xgenerator<xfoobar>` everywhere next to `using foobar = xmaterialize<xfoobar>` .
- Similarly for template widget types, `template <class T> using slider = xmaterialize<xslider, T>`.
The new syntax is
```cpp
auto s = xw::slider_generator<double>()
.min(20.0)
.max(50.0)
.value(30.0)
.finalize();
```
=> Introduction of xgenerator

include/xwidgets/xcontroller.hpp, include/xwidgets/xmaterialize.hpp, include/xwidgets/xnumeral.hpp, include/xwidgets/xobject.hpp, include/xwidgets/xprogress.hpp, include/xwidgets/xselection.hpp, include/xwidgets/xselectionslider.hpp, include/xwidgets/xslider.hpp
Another method instead of defining `self` would be to have the `concrete_type` typedef in all widgets alongside `derived_type` and make all the properties take a `concrete_type` instead of a `derived_type` template property.
=> Use concrete_type for registering validators and observers in constructors

include/xwidgets/xlink.hpp
After the update of `json` in xeus 0.8.2.
=> Remove std pair to_json and from_json overloads

CMakeLists.txt
CMake fails on line CMakeLists.txt:109 with cmake before 3.8
See https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html
@JohanMabille
=> Fix cmake required version

docs/source/compilers.rst, include/xwidgets/xholder.hpp, include/xwidgets/xmaterialize.hpp
This seems to be impacted by https://github.com/vgvassilev/cling/issues/180#issuecomment-380125484 even with the fix in https://github.com/root-project/cling/pull/225.
```
input_line_15:2:59: error: use of undeclared identifier 'xtransport'; did you mean 'xw::xtransport'?
mime_bundle_repr(*(*(std::__1::__vector_base<xw::xholder<xtransport>, std::__1::allocator<xw::xholder<xtransport> > >::value_type**)0x7ffee5a05c80));
^~~~~~~~~~
xw::xtransport
/Users/scorlay/miniconda3/include/xwidgets/xtransport.hpp:85:11: note: 'xw::xtransport' declared here
class xtransport
```
We had to add an alias template for xtransport in the general namespace for the case of cling.
=> Add mime bundle repr for xholders

include/xwidgets/xbox.hpp, include/xwidgets/xholder.hpp, include/xwidgets/xtransport.hpp, test/test_xholder.cpp, test/test_xwidgets.cpp
This make the use of `xholder_shared` hidden, as discussed in #150
=> shared holder api

include/xwidgets/xbinary.hpp
This allows for the buffer paths in xvolume, e.g. `{"x", "0", "buffer"}` where the json looks like 
`{x: [ {buffer: ..., dtype: ... } ] };`
=> parse integers in buffer paths for array indexing

docs/source/compilers.rst
Fix some quotes in the compiler docs.
=> Compiler Docs: Fix Quotes

include/xwidgets/xbinary.hpp
This fixes https://github.com/QuantStack/xwebrtc/issues/8.
When the `ximage` value is set from the frontend, it's not correctly set on the backend.
=> WIP - Fix ximage

include/xwidgets/xtransport.hpp
This member was never used and not reachable from other classes.
Removing it slightly reduces the size of the binary (1.2%)
=> Removed unused member m_message_callback

CMakeLists.txt
We were running `find_package(cppzmq)` while not really using the target in the cmake. Removing that line.
=> Relax cppzmq dependency

include/xwidgets/xeither.hpp
This fixes #191 crash by using templates and parameter packs rather
than using the preprocessor to process xeither.
=> fix to #191 by templatizing lambda

CMakeLists.txt, include/xwidgets/xcommon.hpp, include/xwidgets/xmedia.hpp, include/xwidgets/xobject.hpp, include/xwidgets/xtransport.hpp, include/xwidgets/xwidget.hpp, src/xcommon.cpp
@serge-sans-paille
Binary sizes (both using xproperty master, which already improves thind a lot:):
- before: 3147264 (2210176 stripped)
- after: 2771664 (1923400 stripped)
=> Refactor xtransport

include/xwidgets/xobject.hpp, include/xwidgets/xtransport.hpp
This further reduces the binary size.
Before: 2 419 720 (1 688 392 stripped)
After: 2 255 824 (1 598 280 stripped)
=> No double CRTP

CMakeLists.txt
I removed two lines from the main `CMakeLists.txt` that always forced the build in Release mode for building the tests even though tests are not enabled.
The same lines can be found in the `test/CMakeLists.txt` file so I think they're just a leftover.
=> Fix cmake build type being always set to Release

include/xwidgets/xbox.hpp, include/xwidgets/xlink.hpp
this allows to use xwidgets in conjunction with a dynamic language a la lua.
With that:
* widgets can be added via id (ie in a typeless fashion) to layouts (ie to xbox or derived classes)
* xlink / xdirectional_link can be constructed from `xholder`(ie in a typeless fashion)
=> added function to add widgets via id and link widgets via holder

include/xwidgets/xcommon.hpp, include/xwidgets/xtransport.hpp, include/xwidgets/xwidgets_config.hpp, src/xcommon.cpp
- Add comments around the update protocol
- Unconditionally send echo_update on front_end change
- Update protocol version
=> Update to protocol 2.1.0 (echo_update)

include/xwidgets/xbinary.hpp, include/xwidgets/xcommon.hpp, include/xwidgets/xcontroller.hpp, include/xwidgets/xholder.hpp, include/xwidgets/xregistry.hpp, src/xbinary.cpp, src/xcommon.cpp, src/xholder.cpp, src/xholder_id.cpp, src/xregistry.cpp, src/xtarget.cpp, src/xtarget.hpp
A few changes to get this going.
~~The implementation is currently leaking, as are all currently all things created from the frontend, even after they are closed (owning `xholder`s).
Perhaps better to address that in a separate PR~~
A simple fix is proposed to manage comm closed by the front-end, but the fix is sensitive to Xeus modification.
The protocol implemented is the one used in IPyWidget, but not the one documented. Tracking in
https://github.com/jupyter-widgets/ipywidgets/issues/3441
=> Implement juyter.widget.control protocol

README.md
Dear maintainers,
I am experimenting with `xwidgets` with jupyter lab 4.0.8 and xeus-cling 0.15.1 
I successfully installed it following the documentation with
```
mamba install xwidgets -c conda-forge
```
The `README.md` specifies that to use the widgets in jupyterlab it is necessary to install the related extension, but when I run
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
a deprecation warning and an error are thrown
```
Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.
Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages …
```
=> Remove  JupyterLab extension install from README.md

CMakeLists.txt, include/xwidgets/xwidgets_config.hpp, include/xwidgets/xwidgets_config_cling.hpp.in
We have been using xwidgets in xeus-cpp-lite through a shared build (libxwidgets.so) 
The patch can be found here : https://github.com/emscripten-forge/recipes/pull/2402
This PR upstreams the patch involved and would need a release to get rid of the same on emscripten-forge.
=> Enable xwidgets with xeus-cpp-lite
